// pass env vars to browser so that they can be accessed as process.env.var in the code
// another way to do it is to prefix the env names with NEXT_PUBLIC_
module.exports = {
    env: {
      REACT_APP_AUTH_SCHEME: process.env.REACT_APP_AUTH_SCHEME,
      REACT_APP_API_URL: process.env.REACT_APP_API_URL,
      REACT_APP_AUTH_REDIRECT_URI: process.env.REACT_APP_AUTH_REDIRECT_URI,
      REACT_APP_AUTH_AUTHORITY_URL_B2B: process.env.REACT_APP_AUTH_AUTHORITY_URL_B2B,
      REACT_APP_AUTH_API_SCOPES_B2B: process.env.REACT_APP_AUTH_API_SCOPES_B2B,
      REACT_APP_AUTH_LOGIN_SCOPES_B2B: process.env.REACT_APP_AUTH_LOGIN_SCOPES_B2B,
      REACT_APP_AUTH_CLIENT_ID_B2B: process.env.REACT_APP_AUTH_CLIENT_ID_B2B,
      REACT_APP_AUTH_VALIDATE_AUTHORITY_B2B: process.env.REACT_APP_AUTH_VALIDATE_AUTHORITY_B2B,
      REACT_APP_AUTH_AUTHORITY_URL_B2C: process.env.REACT_APP_AUTH_AUTHORITY_URL_B2C,
      REACT_APP_AUTH_API_SCOPES_B2C: process.env.REACT_APP_AUTH_API_SCOPES_B2C,
      REACT_APP_AUTH_LOGIN_SCOPES_B2C: process.env.REACT_APP_AUTH_LOGIN_SCOPES_B2C,
      REACT_APP_AUTH_CLIENT_ID_B2C: process.env.REACT_APP_AUTH_CLIENT_ID_B2C,
      REACT_APP_AUTH_VALIDATE_AUTHORITY_B2C: process.env.REACT_APP_AUTH_VALIDATE_AUTHORITY_B2C,
      REACT_APP_AUTH_DOMAIN_NAME: process.env.REACT_APP_AUTH_DOMAIN_NAME,
    }
  };